# Generated by Django 5.2.3 on 2025-08-29 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employe',
            name='salaire_base',
        ),
    ]
