# Generated by Django 5.2.3 on 2025-08-29 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0002_remove_employe_salaire_base'),
    ]

    operations = [
        # Ajouter d'abord les champs nécessaires
        migrations.AddField(
            model_name='configurationsalaire',
            name='statut_presence',
            field=models.CharField(default='P(Am_&_Pm)', max_length=50, verbose_name='Statut de présence'),
        ),
        migrations.AddField(
            model_name='configurationsalaire',
            name='montant_journalier',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant journalier (GNF)'),
        ),
        migrations.AddField(
            model_name='configurationsalaire',
            name='actif',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        # Mettre à jour le champ statut de PresenceJournaliere
        migrations.AlterField(
            model_name='presencejournaliere',
            name='statut',
            field=models.CharField(blank=True, choices=[('P(Am)', 'Présent matin'), ('P(Pm)', 'Présent après‑midi'), ('P(Am_&_Pm)', 'Présent matin & après‑midi'), ('P(dim_Am)', 'Présent dimanche matin'), ('P(dim_Pm)', 'Présent dimanche après‑midi'), ('P(dim_Am_&_Pm)', 'Présent dimanche matin & après‑midi'), ('A', 'Absent'), ('M', 'Malade'), ('M(Payer)', 'Malade (payé)'), ('OFF', 'Repos')], default='P(Am_&_Pm)', max_length=50, null=True, verbose_name='Statut'),
        ),
        # Supprimer l'ancien champ obsolète
        migrations.RemoveField(
            model_name='configurationsalaire',
            name='salaire_base',
        ),
        # Enfin, appliquer la contrainte d'unicité qui dépend de 'statut_presence'
        migrations.AlterUniqueTogether(
            name='configurationsalaire',
            unique_together={('employe', 'statut_presence')},
        ),
    ]
