# Generated by Django 5.2.3 on 2025-08-31 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0003_alter_configurationsalaire_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Titre')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
            ],
            options={
                'verbose_name': 'Image de la galerie',
                'verbose_name_plural': 'Images de la galerie',
            },
        ),
    ]
