# Generated by Cascade to fix missing 'titre' column on fleet_app_alerte
from django.db import migrations


def add_titre_column_if_missing(apps, schema_editor):
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        try:
            cursor.execute("PRAGMA table_info(fleet_app_alerte)")
            cols = [row[1] for row in cursor.fetchall()]  # row[1] is column name
            if 'titre' not in cols:
                # Add column with DEFAULT '' to satisfy NOT NULL at model-level later
                cursor.execute("ALTER TABLE fleet_app_alerte ADD COLUMN titre varchar(200) DEFAULT ''")
        except Exception:
            # If anything goes wrong, let migration continue without crashing (no-op)
            # Better to log in real environment
            pass


def noop_reverse(apps, schema_editor):
    # No reverse operation; leaving column is safe
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0004_galleryimage'),
    ]

    operations = [
        migrations.RunPython(add_titre_column_if_missing, noop_reverse),
    ]
