# Generated by Django 5.2.3 on 2025-09-01 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0005_add_titre_to_alerte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='statut',
            field=models.CharField(choices=[('Actif', 'Actif'), ('Inactif', 'Inactif'), ('Suspendu', 'Suspendu'), ('Congé', 'En congé'), ('Formation', 'En formation')], default='Actif', max_length=50, verbose_name='Statut'),
        ),
    ]
