# Generated by Django 4.2.24 on 2025-09-06 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0006_alter_employe_statut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coutfonctionnement',
            name='kilometrage',
        ),
        migrations.AddField(
            model_name='coutfonctionnement',
            name='km_actuel',
            field=models.IntegerField(default=0, verbose_name='Kilométrage actuel'),
        ),
    ]
