# Generated by Django 5.2.6 on 2025-09-09 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0008_chauffeur_user_consommationcarburant_user_and_more'),
    ]

    operations = [
    ]
