# Generated by Django 5.2.6 on 2025-09-24 11:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0010_add_user_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alerte',
            name='user',
        ),
        migrations.RemoveField(
            model_name='feuillederoute',
            name='user',
        ),
        migrations.CreateModel(
            name='FournisseurVehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom du fournisseur')),
                ('contact', models.CharField(blank=True, max_length=150, null=True, verbose_name='Contact')),
                ('telephone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('adresse', models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Fournisseur de véhicule',
                'verbose_name_plural': 'Fournisseurs de véhicules',
            },
        ),
        migrations.CreateModel(
            name='LocationVehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_location', models.CharField(choices=[('Interne', 'Interne'), ('Externe', 'Externe')], max_length=10, verbose_name='Type de location')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('tarif_journalier', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Tarif journalier')),
                ('statut', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Clôturée', 'Clôturée')], default='Active', max_length=10, verbose_name='Statut')),
                ('motif', models.CharField(blank=True, max_length=255, null=True, verbose_name='Motif/Objet')),
                ('fournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet_app.fournisseurvehicule', verbose_name='Fournisseur')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='fleet_app.vehicule', verbose_name='Véhicule')),
            ],
            options={
                'verbose_name': 'Location de véhicule',
                'verbose_name_plural': 'Locations de véhicules',
            },
        ),
        migrations.CreateModel(
            name='FactureLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, verbose_name='Numéro de facture')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date de facture')),
                ('montant_ht', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant HT')),
                ('tva', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='TVA')),
                ('montant_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant TTC')),
                ('statut', models.CharField(choices=[('Brouillon', 'Brouillon'), ('Payée', 'Payée'), ('Annulée', 'Annulée')], default='Brouillon', max_length=20, verbose_name='Statut')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='fleet_app.locationvehicule', verbose_name='Location')),
            ],
            options={
                'verbose_name': 'Facture location',
                'verbose_name_plural': 'Factures location',
            },
        ),
        migrations.CreateModel(
            name='FeuillePontageLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('statut', models.CharField(choices=[('Travail', 'Travail'), ('Entretien', 'Entretien'), ('Hors service', 'Hors service'), ('Inactif', 'Inactif')], default='Travail', max_length=20, verbose_name='Statut du jour')),
                ('commentaire', models.CharField(blank=True, max_length=255, null=True, verbose_name='Commentaire')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feuilles', to='fleet_app.locationvehicule', verbose_name='Location')),
            ],
            options={
                'verbose_name': 'Feuille de pontage',
                'verbose_name_plural': 'Feuilles de pontage',
                'unique_together': {('location', 'date')},
            },
        ),
    ]
