# Generated by Django 5.2.6 on 2025-09-25 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0011_remove_alerte_user_remove_feuillederoute_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturelocation',
            name='jours_non_travail_mois',
            field=models.IntegerField(default=0, verbose_name='Jours non travaillés (mois)'),
        ),
        migrations.AddField(
            model_name='facturelocation',
            name='jours_travail_mois',
            field=models.IntegerField(default=0, verbose_name='Jours de travail (mois)'),
        ),
    ]
