# Generated by Django 5.2.6 on 2025-09-25 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0012_facturelocation_jours_non_travail_mois_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturelocation',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fleet_app.entreprise', verbose_name='Entreprise'),
        ),
        migrations.AddField(
            model_name='feuillepontagelocation',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fleet_app.entreprise', verbose_name='Entreprise'),
        ),
        migrations.AddField(
            model_name='fournisseurvehicule',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fleet_app.entreprise', verbose_name='Entreprise'),
        ),
        migrations.AddField(
            model_name='locationvehicule',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fleet_app.entreprise', verbose_name='Entreprise'),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fleet_app.entreprise', verbose_name='Entreprise'),
        ),
    ]
