# Generated by Django 5.2.6 on 2025-09-25 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0014_backfill_entreprise_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fleet_app.entreprise', verbose_name='Entreprise'),
        ),
        migrations.AddField(
            model_name='entreestock',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fleet_app.entreprise', verbose_name='Entreprise'),
        ),
        migrations.AddField(
            model_name='lignecommande',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fleet_app.entreprise', verbose_name='Entreprise'),
        ),
        migrations.AddField(
            model_name='mouvementstock',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fleet_app.entreprise', verbose_name='Entreprise'),
        ),
        migrations.AddField(
            model_name='produit',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fleet_app.entreprise', verbose_name='Entreprise'),
        ),
        migrations.AddField(
            model_name='sortiestock',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fleet_app.entreprise', verbose_name='Entreprise'),
        ),
    ]
