# Generated by Django 5.2.6 on 2025-09-29 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0016_backfill_inventaire_entreprise'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicule',
            name='fournisseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicules', to='fleet_app.fournisseurvehicule', verbose_name='Fournisseur'),
        ),
    ]
