# Generated by Django 5.2.6 on 2025-10-04 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0017_vehicule_fournisseur'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='valeur_km',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valeur par km (GNF)'),
        ),
        migrations.CreateModel(
            name='FraisKilometrique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('kilometres', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Kilomètres parcourus')),
                ('valeur_par_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valeur par km (GNF)')),
                ('total_a_payer', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total à payer')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description/Trajet')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet_app.employe', verbose_name='Employé')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Frais kilométrique',
                'verbose_name_plural': 'Frais kilométriques',
                'db_table': 'FraisKilometriques',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
