# Generated by Django 5.2.6 on 2025-10-07 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0017_vehicule_fournisseur'),
    ]

    operations = [
        # Migration placeholder pour maintenir la séquence
        # Aucune opération nécessaire
    ]
