# Generated by Django 5.2.6 on 2025-10-05 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0017_vehicule_fournisseur'),
    ]

    operations = [
        migrations.AddField(
            model_name='paieemploye',
            name='montant_frais_kilometriques',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Frais kilométriques (Bonus/Km)'),
        ),
    ]
